name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:26

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run linter
      run: rebar3 lint
    - name: Run tests
      run: rebar3 eunit --cover
    - name: Run cover
      run: rebar3 cover -m 100
